name: GeoLoc
author: TSERATO
version: '2.0'
main: dev.tserato.geoloc.GeoLocSpigot
api-version: '1.20'
softdepend:
  - PlaceholderAPI

commands:
  geoloc:
    description: "Use this to get the IP and Geolocation of players."
    aliases: [geoloc, gl, geol, gloc]